define(function() {

  'use strict';
  
  return {
    byExtension: {
      '7z': 'application/x-7z-compressed',
      ace: 'application/x-ace-compressed',
      adf: 'application/x-amiga-disk-format',
      adz: 'application/gzip; compressed-type=application/x-amiga-disk-format',
      aif: 'audio/x-aiff',
      aiff: 'audio/x-aiff',
      avi: 'video/x-avi',
      bat: 'application/x-bat',
      bmp: 'image/bmp',
      bz: 'application/x-bzip',
      bz2: 'application/x-bzip2',
      class: 'application/x-java-class',
      com: 'application/x-exe-msdos-simple',
      dll: 'application/x-exe-ambiguous',
      dms: 'application/x-disk-masher-system',
      exe: 'application/x-exe-ambiguous',
      flc: 'video/x-flic',
      fli: 'video/x-flic',
      flv: 'video/x-flv',
      gif: 'image/gif',
      hlp: 'application/x-winhelp',
      ico: 'image/x-icon',
      jpg: 'image/jpeg',
      jpeg: 'image/jpeg',
      lha: 'application/x-lha',
      mid: 'audio/midi',
      midi: 'audio/midi',
      mov: 'video/quicktime',
      ogg: 'application/ogg',
      pct: 'image/x-pict',
      pcx: 'image/x-pcx',
      pic: 'image/x-pict',
      pict: 'image/x-pict',
      png: 'image/png',
      psd: 'image/x-photoshop',
      rar: 'application/x-rar-compressed',
      rsrc: 'application/x-mac-resource-fork',
      sit: 'application/x-stuffit',
      swf: 'application/x-shockwave-flash',
      tar: 'application/x-tar',
      tgz: 'application/gzip; compressed-type=application/x-tar',
      tiff: 'image/tiff',
      wav: 'audio/x-wav',
      wri: 'application/x-mswrite',
      zip: 'application/zip',
    },
    byMacResourceType: {
      '8BIM': 'image/x-photoshop-image-resource-block',
      ACHR: 'application/x-world-builder-character',
      ACOD: 'application/x-world-builder-code',
    },
    byMacFileType: {
      AIFF: 'audio/x-aiff',
      MOOV: 'video/quicktime',
      MV93: 'application/x-director',
      'M!93': 'application/x-director',
    },
  };

});
