define(['Format'], function(Format) {

  'use strict';
  
  return {
    '7z': Format('application/x-7z-compressed'),
    ace: Format('application/x-ace-compressed'),
    adf: Format('application/x-amiga-disk-format'),
    adz: Format('application/gzip; encoded="application/x-amiga-disk-format"'),
    aif: Format('audio/x-aiff'),
    aiff: Format('audio/x-aiff'),
    au: Format('audio/basic'),
    avi: Format('video/x-avi'),
    bat: Format('application/x-bat'),
    bmp: Format('image/bmp'),
    bz: Format('application/x-bzip'),
    bz2: Format('application/x-bzip2'),
    cdy: Format('application/vnd.cinderella'),
    chm: Format('application/vnd.ms-htmlhelp'),
    class: Format('application/x-java-class'),
    com: Format('application/x-exe-msdos-simple'),
    css: Format('text/css'),
    csv: Format('text/csv'),
    dll: Format('application/x-exe-ambiguous'),
    dls: Format('multipart/x-riff; expect=downloadable-sounds'),
    dms: Format('application/x-disk-masher-system'),
    doc: Format('application/x-doc-ambiguous'),
    docx: Format('application/vnd.openxmlformats-officedocument.wordprocessingml.document'),
    dsk: Format('volume/ambiguous'),
    emf: Format('image/emf'),

    //exe: 'application/x-exe-ambiguous',
    exe: Format('application/x-ags-container'),

    flc: Format('video/x-flic'),
    fli: Format('video/x-flic'),
    flv: Format('video/x-flv'),
    gif: Format('image/gif'),
    hlp: Format('application/x-winhelp'),
    htm: Format('text/html'),
    html: Format('text/html'),
    ico: Format('image/vnd.microsoft.icon'),
    img: Format('volume/ambiguous'),
    ini: Format('application/x-ini'),
    iso: Format('volume/optical-media'),
    jar: Format('application/zip'),
    jpg: Format('image/jpeg'),
    jpeg: Format('image/jpeg'),
    js: Format('application/js'),
    json: Format('application/json'),
    lha: Format('application/x-lha'),
    markdown: Format('text/markdown'),
    md: Format('text/markdown'),
    mid: Format('audio/midi'),
    midi: Format('audio/midi'),
    mp1: Format('audio/mpeg; layer=1'),
    mp2: Format('audio/mpeg; layer=2'),
    mp3: Format('audio/mpeg; layer=3'),
    mov: Format('video/quicktime'),
    ogg: Format('application/ogg'),
    otf: Format('application/font-sfnt'),
    pct: Format('image/x-pict'),
    pcx: Format('image/vnd.zbrush.pcx'),
    pdf: Format('application/pdf'),
    pic: Format('image/x-pict'),
    pict: Format('image/x-pict'),
    png: Format('image/png'),
    ppt: Format('application/vnd.ms-powerpoint'),
    ps: Format('application/postscript'),
    psd: Format('image/x-photoshop'),
    rar: Format('application/vnd.rar'),
    rsrc: Format('application/x-mac-resource-fork'),
    rtf: Format('application/rtf'),
    sit: Format('application/x-stuffit'),
    swf: Format('application/x-shockwave-flash'),
    tar: Format('application/x-tar'),
    tga: Format('image/x-targa'),
    tgz: Format('application/gzip; encoded="application/x-tar"'),
    tiff: Format('image/tiff'),
    ttf: Format('application/font-sfnt'),
    toast: Format('volume/optical-media'),
    txt: Format('text/plain'),
    wav: Format('audio/x-wav'),
    wmf: Format('image/wmf'),
    wri: Format('application/x-mswrite'),
    xls: Format('application/vnd.ms-excel'),
    xlsx: Format('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'),
    zip: Format('application/zip'),
    zzt: Format('application/x-zzt'),
  };

});
